### ISSUE TITLE
Uncaught Exception Error: Class "NetworkequipmentType" not found in /var/www/glpi/marketplace/purchaserequest/setup.php at line 63

### ISSUE THREAD

**Issue by Megachip** [InfotelGLPI/purchaserequest#4]
3.0.0-rc2 from store isn't compatible with 10.0.0-rc1

**Comment by Megachip** [comment]
maybe the same like issue #2

**Comment by tsmr** [comment]
Try with https://github.com/InfotelGLPI/purchaserequest/releases/tag/3.0.0-rc3
