### ISSUE TITLE
Amount field not in good format

### ISSUE THREAD

**Issue by ThierryLam** [InfotelGLPI/purchaserequest#7]
Hello,

I think there is a problem on the format of the amount field :
- It is an integer. Amount can be a float.
- It has a limit of 10000. A purchase request can be done on greater amount.
- The field is a dropdown, I think it should be a simple text zone

It would be great if you can make these changes.

Regards,

Thierry.

**Comment by tsmr** [comment]
Fixed in 3.0.2 version
